# Generated by Django 4.2.4 on 2023-08-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('SKU', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=60)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
            ],
        ),
    ]
