# Generated by Django 4.2.4 on 2023-08-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiusuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='producto_comprar',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='producto_vender',
        ),
    ]
